This file contains ramblings and design ideas for shsl

* lang
** types
There are the following types
- integer (long)
- real (double)
- string (null terminated char*)
- symbol (also null terminated char*)
these are all tagged pointers
(todo: intern the symbols?)
- cons
this is a (tagged?) pair of tagged pointers  

do I make struct cons that's like, a pair of these?
and then have a cons value that's a tagged pointer to a cons struct?

I think that might make sense,
it's gonna be a pain in the ass to wrangle cons cells like that, but it should make handling cons cells and other values through a uniform interface much easier for the garbage collection part

** syntax
I'm thinking of copying some clojure syntax for shsl, clojure seems like a good syntax for scripty shit
basically I'm thinking
fn - defn - and %(%1 %2 %3) for function definitions, short and to the point
[ ] for vector "literals"
{ } for map "literals"

although I'm still gonna pull a bunch of shit from cl instead
from ~shsl.lisp~ 
#+begin_src lisp
;; I want the following lispy shit
;; if let do lambda defvar defun defmacro set setq progn
;; TODO: lambda lists?

;; and the following scripty shit
;; while until
#+end_src

* roadmap
- [ ] finish the lisp version/prototype
  - [ ] lisp parser
  - [ ] lisp evaluator
- [ ] do a (leaky) c/c++ version
  - [ ] c parser
  - [ ] c evaluator
- [ ] garbage collection
  - [ ] design generic interface
    - [ ] refcounted
    - [ ] mark and sweep
    - [ ] compacting

(there will likely be a /lot/ of garbage collection prototyping as well, shall be added to the roadmap when I figure out how will I prototype the gc)      

** c or c++?
I might have a small problem
basically
- a C version is gonna be a lot easier to integrate with a whole load of different shit, because everyone is forced to know how to speak C
- a C++ version is gonna be easier to develop because I'd have a builtin fucking hash maps for the variable lookup

I could solve this by just stealing a c impl of a hash map and shoving that in the implementation for the evaluator

** garbage collection
Go steal the garbage collection handbook for the garbage collection part,
might wanna have a generic garbage collection interface (have the same ~.h~ used by the runtime, then have different ~.c~s that implement it)

The garbage collection interface could be like.
#+begin_src c
  shsl_gc_t shsl_gc_init(size_t heap_size);

  // returns a nullptr on out of memory
  void* shsl_gc_alloc(shsl_gc_t* gc, size_t size);
  // runs reclaimation cycle, retruns wether it was successful
  bool shsl_gc_reclaim(shsl_gc_t* gc);

  // and maybe(?)
  // release ptr (should I have a more general "thing managed by gc" struct?)
  void shsl_gc_release(shsl_gc_t* gc, void* ptr);
  // further TODO:
  // how the fuck do I mark the roots?
#+end_src

Another idea would be to have a specific-ish struct for shit managed by the garbage collector.

Basically, I want an interface that can be implemented by all the following possible collectors
- mark and sweep
- compacting/lisp2 gc
- reference counting
- the null garbage collector (just leak, who gives a shit)

And I want it to be transparent to the gc library user which of these collectors is actually running in the background.
This is because I'll have to be the user for this shit and I want to be able to develop and test different collectors against the same interpreter code without wanting to fucking die.

* single header?
I have two ideas at the moment for how to make shsl an actually single header scripting library
- develop the entire thing in one file a-la stb
- develop the thing in separate files (have separate ~parse.h~, ~parse.c~, ~eval.h~, ~eval.c~, ~gc.h~, ~gc.c~ files), then have a bash script or some shit to create the single header version
  something like an stb_ equivalent of the sqlite3 amalgam, a potential script to do it might look like the following
  #+begin_src bash
    SRC_DIR="src/"
    OUTPUT_AMALGAM="./shsl.h"

    # https://linuxize.com/post/bash-heredoc/
    # "this file is generated" note, and file level preprocessor shit
    cat <<EOF > "$OUTPUT_AMALGAM"
    /* this file is an amalgam generated from a bash script
     ,* do not edit this file, to edit the shsl source code edit the files
     ,* in the src/ directory instead, then run the ./generate_amalgam script to
     ,* to generate this amalgam
     ,*/

    #ifndef SHSL_INCLUDE_HEADER
    #define SHSL_INCLUDE_HEADER

    #ifdef __cplusplus
    extern "C" {
    #endif
    EOF

    # function prototypes
    for f in "$SRC_DIR"/*.h; do
        cat "$f" > "$OUTPUT_AMALGAM"
    done

    # function implementations with stb style preprocessor guard
    echo "#ifdef SHSL_IMPELEMTNATION"
    for f in "$SRC_DIR"/*.c; do
        cat "$f" > "$OUTPUT_AMALGAM"
    done
    echo "#endif // SHSL_IMPELEMTNATION"

    # close the file level preprocessor shit
    cat <<EOF > "$OUTPUT_AMALGAM"
    #ifdef __cplusplus
    }
    #endif
    #endif // SHSL_INCLUDE_HEADER
    EOF
  #+end_src
  this would also allow for the user to pick between which of the two versions are best suited for whatever the fuck the user wants to do, although the main reason for this latter idea is the rather simple fact that I cannot be fucked to edit a file longer than about 300 lines.
  Another advantage of this second approach is that, given that I want to try out different garbage collectors, I can just swap in another ~src/gc.c~ and rerun the script, no weird ifdefs or giant files needed.

* refs
godo, nella ref posso mettere se è mutable
e se manipolo le ref solo con funzioni che accettano ref poi quelle funzioni posso fargli ritornare, /for instance/, ~t~ o un errore
daje

** fixed refs
some references are just pointers that I'm wragling through references
I could add a field to references called like
~fixed~
that controls wether that references can get updates by ref counts and shit

for instance
subexpressions
I can say without much doubt that handling some subexpressions through refcounted pointers has been, for lack of a better word, a fucking mistake
mostly because refcounting as is currently implemented marks just about everything as statey
and just about every state as affecting every other state

which means I need to like, take a far better, far futher look at the various contracts I have between modules as far as reference counts are concerned  
because I handle a lot of references with count 0 in the c code

** mark and sweep

** mark compact
